import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'fabric-loom'
    id 'maven-publish'
    id 'idea'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
    id "com.modrinth.minotaur" version "2.+"
}

base.archivesName = "${mod_id}-fabric"

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(path: ':Common', configuration: 'namedElements')

    modApi group: 'info.journeymap', name: 'journeymap-api-fabric', version: project.journeymap_api_version, changing: true
    modRuntimeOnly "maven.modrinth:journeymap:${project.jm_fabric_version}"

    modImplementation "dev.architectury:architectury-fabric:${project.architectury_version}"
    modImplementation "curse.maven:${project.ftb_library_fabric}"
    modImplementation "curse.maven:${project.ftb_teams_fabric}"
    modImplementation "curse.maven:${project.ftb_chunks_fabric}"
    modImplementation "maven.modrinth:balm:${project.balm_fabric_version}"
    modImplementation "maven.modrinth:waystones:${project.waystones_fabric_version}"
}

loom {
    mixin {
        useLegacyMixinAp = false
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

processResources {
    from project(":Common").sourceSets.main.resources
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project(":Common").sourceSets.main.allSource)
}

jar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${mod_name}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId base.archivesName.get()
            version project.version
            from components.java
        }
    }

    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}

def ENV = System.getenv()
def release_title = "[Fabric] v${version}"
def publishJar = tasks.named("remapJar")

tasks.register("publishCurseForge", TaskPublishCurseForge) {
    apiToken = ENV.CF_TOKEN ?: "notset"
    def mainFile = upload(curse_id, publishJar)
    mainFile.displayName = release_title
    mainFile.releaseType = release_type
    mainFile.addModLoader("Fabric", "Quilt")
    mainFile.addJavaVersion("Java 17")
    mainFile.addGameVersion(minecraft_version)
    mainFile.addEnvironment("Client")
    mainFile.addRequirement("journeymap")
    mainFile.addOptional("ftb-chunks-forge", "waystones")
    mainFile.changelogType = "markdown"
    mainFile.changelog = rootProject.file('changelog.md')
}

modrinth {
    token = ENV.MODRINTH_TOKEN ?: "notset"
    projectId = modrinth_id
    versionType = release_type
    versionName = release_title
    versionNumber = "${version}+fabric"
    uploadFile = publishJar
    gameVersions = [ minecraft_version ]
    loaders = ["fabric", "quilt"]
    changelog = rootProject.file('changelog.md').text
    dependencies {
        required.project "lfHFW1mp" // journeymap
        optional.project "LOpKHB2A" // waystones
    }
}
