plugins {
    id 'fabric-loom' version '1.17-SNAPSHOT' apply false
    id 'net.neoforged.moddev' version '2.0.148' apply false
}


configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

tasks.configureEach { task ->
    if (task instanceof Copy || task instanceof AbstractArchiveTask) {
        task.duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
}