plugins {
    id 'net.neoforged.moddev'
    id 'multiloader-common'
}

configurations {
    commonJava {
        canBeConsumed = true
        canBeResolved = false
    }
    commonResources {
        canBeConsumed = true
        canBeResolved = false
    }
}

artifacts {
    commonJava(sourceSets.main.java.sourceDirectories.singleFile)
    commonResources(sourceSets.main.resources.sourceDirectories.singleFile)
}

test {
    useJUnitPlatform()
}

neoForge {
    neoFormVersion = neo_form_version
}

dependencies {
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    compileOnly project(":api")
    compileOnly group: 'info.journeymap', name: 'journeymap-api-common', version: project.journeymap_api_version,
            changing: true
    compileOnly "net.fabricmc:sponge-mixin:0.16.4+mixin.0.8.7"
    compileOnly "dev.architectury:architectury-neoforge:${project.architectury_version}"
    compileOnly "curse.maven:${project.ftb_library_neoforge}"
    compileOnly "curse.maven:${project.ftb_teams_neoforge}"
    compileOnly "curse.maven:${project.ftb_chunks_neoforge}"

}
