modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/frank89722/JourneyMapIntegration/issues"
[[mods]]
modId="jmi"
version="${file.jarVersion}"
displayName="JourneyMap Integration"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/journeymap-integration"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="frankV"
description='''
The mod that add mod integration for JourneyMap.
'''
[[dependencies.jmi]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jmi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jmi]]
    modId="journeymap"
    mandatory=true
    versionRange="[5.8.0beta8,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.jmi]]
    modId="ftbchunks"
    mandatory=false
    versionRange="[1605.3.x,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jmi]]
    modId="waystones"
    mandatory=false
    versionRange="[7.5.0,)"
    ordering="NONE"
    side="BOTH"
