import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'net.minecraftforge.gradle' version '7.0.34'
    id 'net.minecraftforge.renamer' version '1.1.0'
    id 'net.darkhax.curseforgegradle' version '1.1.+'
    id "com.modrinth.minotaur" version "2.+"
    id 'maven-publish'
}

base.archivesName = "${mod_id}-forge"

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    compileOnly project(":Common")

    implementation renamer.dependency("dev.architectury:architectury-forge:${project.architectury_version}")
    implementation renamer.dependency("curse.maven:${project.ftb_library_forge}")
    implementation renamer.dependency("curse.maven:${project.ftb_teams_forge}")
    implementation renamer.dependency("curse.maven:${project.ftb_chunks_forge}")
    implementation renamer.dependency("maven.modrinth:balm:${project.balm_forge_version}")
    implementation renamer.dependency("maven.modrinth:waystones:${project.waystones_forge_version}")

    compileOnly renamer.dependency("info.journeymap:journeymap-api-forge:${project.journeymap_api_version}")
    implementation renamer.dependency("maven.modrinth:journeymap:${project.jm_forge_version}")
}

minecraft {
    mappings channel: 'official', version: "${minecraft_version}"

    runs {
        configureEach {
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            args "--mixin.config=${mod_id}.mixins.json"
        }
        register('client') {
            workingDir.convention layout.projectDirectory.dir("run")
            systemProperty "mixin.debug.export", "true"
        }
        register('server') {
            workingDir.convention layout.projectDirectory.dir("run")
            args "nogui"
        }
    }
}

renamer.mappings.from minecraft.dependency.toSrgFile

renamer.enableMixinRefmaps { mixin ->
    mixin.source(sourceSets.main, "${mod_id}")
    mixin.jar(tasks.named('jar'))
}

def reobfJar = renamer.classes(tasks.named('jar', Jar)) {
    map.from minecraft.dependency.toSrgFile
    output = tasks.named('jar', Jar).flatMap { it.archiveFile }
}
tasks.named('jar', Jar) {
    finalizedBy reobfJar
}
tasks.matching { it.name.startsWith('publish') || it.name.startsWith('modrinth') || it.name.startsWith('generate') }.configureEach {
    mustRunAfter reobfJar
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

tasks.named("compileJava", JavaCompile) {
    source(project(":Common").sourceSets.main.allSource)
}

processResources {
    from project(":Common").sourceSets.main.resources
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : mod_name,
                'Specification-Vendor'    : mod_author,
                'Specification-Version'   : project.jar.archiveVersion,
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_author,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'Timestamp'               : System.currentTimeMillis(),
                'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                'Build-On-Minecraft'      : minecraft_version,
                'MixinConfigs'            : "${mod_id}.mixins.json"
        ])
    }
}

def ENV = System.getenv()
def release_title = "[Forge] v${version}"
def publishJar = tasks.named("jar")

tasks.register("curseforge", TaskPublishCurseForge) {
    apiToken = ENV.CF_TOKEN ?: "notset"
    def mainFile = upload(curse_id, publishJar)
    mainFile.displayName = release_title
    mainFile.releaseType = release_type
    mainFile.addModLoader("Forge")
    mainFile.addJavaVersion("Java 17")
    mainFile.addGameVersion(minecraft_version)
    mainFile.addEnvironment("Client")
    mainFile.addRequirement("journeymap")
    mainFile.addOptional("ftb-chunks-forge", "waystones")
    mainFile.changelogType = "markdown"
    mainFile.changelog = rootProject.file('changelog.md')
}

modrinth {
    token = ENV.MODRINTH_TOKEN ?: "notset"
    projectId = modrinth_id
    versionType = release_type
    versionName = release_title
    versionNumber = "${version}+forge"
    uploadFile = publishJar
    gameVersions = [ minecraft_version ]
    loaders = ["forge"]
    changelog = rootProject.file('changelog.md').text
    dependencies {
        required.project "lfHFW1mp" // journeymap
        optional.project "LOpKHB2A" // waystones
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
