modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/frank89722/JourneyMapIntegration/issues"
[[mods]]
modId = "jmi"
version = "${file.jarVersion}"
displayName = "JourneyMap Integration"
displayTest = "IGNORE_ALL_VERSION"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/journeymap-integration"
#logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors = "frankV"
description = '''
The mod that adds mod integration for JourneyMap.
'''
[[dependencies.jmi]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jmi]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jmi]]
modId = "journeymap"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.jmi]]
modId = "ftbchunks"
type = "optional"
versionRange = "[2101.1.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.jmi]]
modId = "waystones"
type = "optional"
versionRange = "[21.0.0,)"
ordering = "NONE"
side = "CLIENT"


[[mixins]]
config = "jmi.mixins.json"