modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL = "https://github.com/frank89722/JourneyMapIntegration/issues"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayTest = "IGNORE_ALL_VERSION"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/journeymap-integration"
#logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors = "frankV"
description = '''${description}'''
[[dependencies.jmi]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.jmi]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.jmi]]
modId = "journeymap"
type = "required"
versionRange = "${journeymap_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.jmi]]
modId = "ftbchunks"
type = "optional"
versionRange = "${ftb_chunks_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.jmi]]
modId = "waystones"
type = "optional"
versionRange = "${waystones_version_range}"
ordering = "NONE"
side = "CLIENT"


[[mixins]]
config = "jmi.mixins.json"