plugins {
    id 'net.neoforged.moddev'
    id 'multiloader-loader'
    id 'io.github.CDAGaming.cursegradle' version '1.+'
    id "com.modrinth.minotaur" version "2.+"
}

neoForge {
    version = project.neoforge_version

//    parchment {
//        mappingsVersion = project.mappings_mc_version
//        minecraftVersion = project.mappings_date
//    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'mixin.debug.export', 'true'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${path})"
        }

        client {
            client()
            gameDirectory = file('run/client')
            //        programArguments = ['--username', 'Dev###']
        }

        server {
            server()
            gameDirectory = file('run/server')
            programArgument '--nogui'
        }

    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}


compat 'ftbchunks', 'waystones'

dependencies {
    implementation "dev.architectury:architectury-neoforge:${project.architectury_version}"

    implementation "curse.maven:${project.ftb_library_neoforge}"
    implementation "curse.maven:${project.ftb_teams_neoforge}"
    implementation "curse.maven:${project.ftb_chunks_neoforge}"
    implementation "maven.modrinth:balm:${project.balm_neoforge_version}"
    implementation "maven.modrinth:waystones:${project.waystones_neoforge_version}"

    api group: 'info.journeymap', name: 'journeymap-api-neoforge', version: project.journeymap_api_version, changing:
            true
    implementation "maven.modrinth:journeymap:${project.jm_neoforge_version}"

}

def ENV = System.getenv()
def release_title = "[NeoForge] v${version}"

if (ENV.CF_TOKEN) {
    curseforge {
        apiKey = ENV.CF_TOKEN
        project {
            id = curse_id
            releaseType = release_type
            addGameVersion "NeoForge"
            addGameVersion "Java 21"
            addGameVersion "Client"
            addGameVersion minecraft_version
            mainArtifact(jar) {
                it.displayName = release_title
            }
            relations {
                it.requiredDependency 'journeymap'
                it.optionalDependency 'ftb-chunks-forge'
                it.optionalDependency 'waystones'
            }
            changelog = rootProject.file('changelog.md')
            changelogType = 'markdown'
        }
    }
}

if (ENV.MODRINTH_TOKEN) {
    modrinth {
        token = ENV.MODRINTH_TOKEN
        projectId = modrinth_id
        versionType = release_type
        versionName = release_title
        versionNumber = "${version}+neoforge"
        uploadFile = jar
        gameVersions = [minecraft_version]
        changelog = rootProject.file('changelog.md').text
        dependencies {
            required.project "lfHFW1mp" // journeymap
            optional.project "LOpKHB2A" // waystones
        }
    }
}
