plugins {
    id 'net.neoforged.moddev'
    id 'multiloader-common'
}

configurations {
    commonJava {
        canBeConsumed = true
        canBeResolved = false
    }
    commonResources {
        canBeConsumed = true
        canBeResolved = false
    }
}

artifacts {
    commonJava(sourceSets.main.java.sourceDirectories.singleFile)
    commonResources(sourceSets.main.resources.sourceDirectories.singleFile)
}

test {
    useJUnitPlatform()
}

neoForge {
    neoFormVersion = neo_form_version
}

dependencies {
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    compileOnly group: 'info.journeymap', name: 'journeymap-api-common', version: project.journeymap_api_version, changing: true
}
