# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and upload to CF

on:
  push:
    branches: [ 1.18.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    if: |
      contains(github.event.head_commit.message, '[build]')

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}

      - name: Changelog
        uses: metcalfc/changelog-generator@v1.0.0
        id: Changelog
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}
          release_name: ${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: "CF Release"
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CHANGELOG: ${{ steps.Changelog.outputs.changelog }}
        run: ./gradlew build curseforge
